403

diff --git a/.github/workflows/wkflw-501-Apply.yml b/.github/workflows/wkflw-501-Apply.yml
--- a/.github/workflows/wkflw-501-Apply.yml
+++ b/.github/workflows/wkflw-501-Apply.yml
@@ -118,12 +118,11 @@ jobs:
             ssh -i ~/.ssh/myKeys ubuntu@$ip "sudo usermod -aG docker ubuntu"
             done
 
-      - name: create prometheus.yml on ec2 instances, on_typ2
+      - name: pre-create prometheus.yml on ec2 instances, on_typ2
         run: |
-            for ip in $(terraform output -json public_ips_typ2 | jq -r ".[]"); do
-              sed "s/{{TARGET_IP}}/$ip/g" files/prometheus.yml.tpl > /tmp/prometheus_$ip.yml
-              scp -i ~/.ssh/myKeys /tmp/prometheus_$ip.yml ubuntu@$ip:/home/ubuntu/prometheus.yml
-            done
+            pwd
+            ls -la
+            ls -la Frontend/files/ || echo "Frontend/files not found here"
 
       - name: create prometheus.yml with all node_exporter targets, on_typ2
         run: |
